"""
This test approximates the run of Copycat described on pages 105-108
of Mitchell 1993 'Analogy Making as Perception'
where Copycat responds to the problem
abc -> abd ==> kji -> ?
with the answer
kjh
In this test, codelets are selected deterministically in order to
test interactions between codelets and workspace work correctly
The test was initially generated by Codex using GPT 5.6 with extra high reasoning
"""
from random import choice as random_choice
from random import choices as random_choices

from copycat import Copycat
from copycat.answer_builder import AnswerBuilder
from copycat.codelet_result import Finish, Fizzle, FizzleReason
from copycat.codelets import (
    BottomUpBondScout,
    BottomUpCorrespondenceScout,
    Breaker,
    ReplacementFinder,
    RuleScout,
    RuleTranslator,
    WholeStringGroupScout,
)
from copycat.codelets.builders import (
    BondBuilder,
    CorrespondenceBuilder,
    DescriptionBuilder,
    GroupBuilder,
    RuleBuilder,
)
from copycat.codelets.scouts.description_scouts import TopDownDescriptionScout
from copycat.codelets.strength_testers import (
    BondStrengthTester,
    CorrespondenceStrengthTester,
    DescriptionStrengthTester,
    GroupStrengthTester,
    RuleStrengthTester,
)


SLIPNET_JSON_FILE = "configs/slipnet.json"
CODERACK_JSON_FILE = "configs/coderack.json"
HYPERPARAMETERS_FILE = "configs/hyperparameters.json"


def test_single_run(monkeypatch):
    copycat = Copycat.from_json(
        SLIPNET_JSON_FILE, CODERACK_JSON_FILE, HYPERPARAMETERS_FILE
    )
    copycat._add_letters_to_workspace("abc -> abd ==> kji -> ?")
    copycat._add_initial_descriptions_to_workspace()
    copycat._post_initial_codelets()

    selected_codelet = [None]
    chosen_object = [None]
    monkeypatch.setattr(
        "copycat.coderack.random.choice",
        lambda population: (
            selected_codelet[0]
            if selected_codelet[0] in population
            else chosen_object[0]
            if chosen_object[0] in population
            else random_choice(population)
        ),
    )
    monkeypatch.setattr(
        "copycat.coderack.random.choices",
        lambda population, weights=None, k=1: (
            [copycat.coderack.get_urgency_bin(selected_codelet[0].urgency_bin)]
            if population is copycat.coderack._urgency_bins
            else random_choices(population, weights=weights, k=k)
        ),
    )
    monkeypatch.setattr(
        "copycat.codelets.strength_testers.bond_strength_tester.random.random",
        lambda: 0.0,
    )
    monkeypatch.setattr(
        "copycat.codelets.strength_testers.group_strength_tester.random.random",
        lambda: 0.0,
    )
    monkeypatch.setattr(
        "copycat.codelets.strength_testers.correspondence_strength_tester.random.random",
        lambda: 0.0,
    )
    monkeypatch.setattr(
        "copycat.codelets.strength_testers.rule_strength_tester.random.random",
        lambda: 0.0,
    )
    monkeypatch.setattr(
        "copycat.codelets.strength_testers.description_strength_tester.random.random",
        lambda: 0.0,
    )

    a, b, c = copycat.workspace.initial_string.letters
    k, j, i = copycat.workspace.target_string.letters
    chosen_object[0] = c
    selected_codelet[0] = next(
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, ReplacementFinder)
    )
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 1
    assert c.replacement.target.letter_category is copycat.slipnet["d"]

    coderack_population = copycat.coderack.population
    for codelet_index in range(25):
        selected_codelet[0] = ReplacementFinder(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(
            FizzleReason.LETTER_ALREADY_HAS_REPLACEMENT
        )
        assert copycat.coderack.number_of_codelets_run == codelet_index + 2
        assert copycat.coderack.population == coderack_population
    chosen_object[0] = None
    for codelet_index in range(25):
        selected_codelet[0] = WholeStringGroupScout(
            2, copycat.coderack, copycat.slipnet, copycat.workspace
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(FizzleReason.NO_BONDS)
        assert copycat.coderack.number_of_codelets_run == codelet_index + 27
        assert copycat.coderack.population == coderack_population
    for codelet_index in range(25):
        selected_codelet[0] = Breaker(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(FizzleReason.NO_STRUCTURES)
        assert copycat.coderack.number_of_codelets_run == codelet_index + 52
        assert copycat.coderack.population == coderack_population

    # Pages 106-108: abc is a left-going predecessor group, while kji is a
    # left-going successor group.  The shared spatial direction preserves the
    # vertical correspondences while predecessor slips to successor.
    for codelet_index, (source, target, category) in enumerate(
        (
            (b, a, "predecessor"),
            (c, b, "predecessor"),
            (j, k, "successor"),
            (i, j, "successor"),
        )
    ):
        selected_codelet[0] = BottomUpBondScout(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        monkeypatch.setattr(
            copycat.workspace, "choose_object", lambda *_, source=source: source
        )
        monkeypatch.setattr(
            source, "choose_neighbor", lambda *_, target=target: target, raising=False
        )
        monkeypatch.setattr(
            selected_codelet[0],
            "_choose_bond_facet",
            lambda *_: copycat.slipnet["letter_category"],
        )
        monkeypatch.setattr(
            selected_codelet[0],
            "_get_bond_category",
            lambda *_, category=category: copycat.slipnet[category],
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 77 + codelet_index * 3
        assert (
            source.string.proposed_bonds[-1].bond_category is copycat.slipnet[category]
        )
        assert any(
            isinstance(posted, BondStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, BondStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 78 + codelet_index * 3
        assert any(
            isinstance(posted, BondBuilder) for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, BondBuilder)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 79 + codelet_index * 3
        assert (
            source.string.bonds_by_role[source][target].bond_category
            is copycat.slipnet[category]
        )

    assert [
        bond.bond_category.name for bond in copycat.workspace.target_string.bonds
    ] == [
        "successor",
        "successor",
    ]

    for codelet_index, workspace_string in enumerate(
        (copycat.workspace.initial_string, copycat.workspace.target_string)
    ):
        monkeypatch.setattr(
            copycat.workspace,
            "get_random_string",
            lambda workspace_string=workspace_string: workspace_string,
        )
        selected_codelet[0] = WholeStringGroupScout(
            2, copycat.coderack, copycat.slipnet, copycat.workspace
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 89 + codelet_index * 3
        assert len(workspace_string.proposed_groups) == 1
        assert any(
            isinstance(posted, GroupStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, GroupStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 90 + codelet_index * 3
        assert any(
            isinstance(posted, GroupBuilder)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, GroupBuilder)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 91 + codelet_index * 3
        assert workspace_string.groups[-1].spans_whole_string()

    initial_group = copycat.workspace.initial_string.groups[-1]
    target_group = copycat.workspace.target_string.groups[-1]
    assert initial_group.group_category is copycat.slipnet["predecessor_group"]
    assert initial_group.direction_category is copycat.slipnet["left"]
    assert target_group.group_category is copycat.slipnet["successor_group"]
    assert target_group.direction_category is copycat.slipnet["left"]

    # Give both whole-string groups the descriptions drawn in the book.  The
    # group-category and direction descriptions determine whether the final
    # correspondence preserves or slips the original successor relation.
    group_descriptions = (
        (
            initial_group,
            copycat.slipnet["object_category"],
            copycat.slipnet["group"],
        ),
        (
            initial_group,
            copycat.slipnet["group_category"],
            copycat.slipnet["predecessor_group"],
        ),
        (
            initial_group,
            copycat.slipnet["string_position_category"],
            copycat.slipnet["whole"],
        ),
        (
            initial_group,
            copycat.slipnet["direction_category"],
            copycat.slipnet["left"],
        ),
        (
            initial_group,
            copycat.slipnet["bond_category"],
            copycat.slipnet["predecessor"],
        ),
        (
            initial_group,
            copycat.slipnet["bond_facet"],
            copycat.slipnet["letter_category"],
        ),
        (
            target_group,
            copycat.slipnet["object_category"],
            copycat.slipnet["group"],
        ),
        (
            target_group,
            copycat.slipnet["group_category"],
            copycat.slipnet["successor_group"],
        ),
        (
            target_group,
            copycat.slipnet["string_position_category"],
            copycat.slipnet["whole"],
        ),
        (
            target_group,
            copycat.slipnet["direction_category"],
            copycat.slipnet["left"],
        ),
        (
            target_group,
            copycat.slipnet["bond_category"],
            copycat.slipnet["successor"],
        ),
        (
            target_group,
            copycat.slipnet["bond_facet"],
            copycat.slipnet["letter_category"],
        ),
    )
    for codelet_index, (group, description_type, descriptor) in enumerate(
        group_descriptions
    ):
        monkeypatch.setattr(
            copycat.workspace, "choose_object", lambda *_, group=group: group
        )
        monkeypatch.setattr(
            description_type,
            "get_possible_descriptors",
            lambda *_, descriptor=descriptor: [descriptor],
        )
        selected_codelet[0] = TopDownDescriptionScout(
            2,
            copycat.coderack,
            copycat.slipnet,
            copycat.workspace,
            description_type,
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 95 + codelet_index * 3
        assert any(
            isinstance(posted, DescriptionStrengthTester)
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, DescriptionStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 96 + codelet_index * 3
        assert any(
            isinstance(posted, DescriptionBuilder)
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, DescriptionBuilder)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 97 + codelet_index * 3
        if description_type in (
            copycat.slipnet["bond_category"],
            copycat.slipnet["bond_facet"],
        ):
            assert any(
                description.facet is description_type
                and description.descriptor is descriptor
                for description in group.bond_descriptions
            )
        else:
            assert group.get_descriptor(description_type) is descriptor

    monkeypatch.setattr(
        copycat.workspace.initial_string, "choose_object", lambda **_: initial_group
    )
    monkeypatch.setattr(
        copycat.workspace.target_string, "choose_object", lambda **_: target_group
    )
    selected_codelet[0] = BottomUpCorrespondenceScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 131
    assert len(copycat.workspace.proposed_correspondences) == 1
    assert any(
        isinstance(posted, CorrespondenceStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 132
    copycat.slipnet.update_activations()
    assert any(
        isinstance(posted, CorrespondenceBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 133
    assert initial_group.correspondence is target_group.correspondence
    assert {
        (mapping.descriptor_1.name, mapping.descriptor_2.name)
        for mapping in initial_group.correspondence.concept_mappings
    }.issuperset(
        {
            ("predecessor_group", "successor_group"),
            ("left", "left"),
            ("predecessor", "successor"),
        }
    )

    for codelet_index, letter in enumerate((a, b)):
        chosen_object[0] = letter
        selected_codelet[0] = ReplacementFinder(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 134 + codelet_index
        assert letter.replacement.target.letter_category is letter.letter_category

    selected_codelet[0] = RuleScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    monkeypatch.setattr(
        selected_codelet[0],
        "_get_initial_description",
        lambda *_: next(
            description
            for description in c.descriptions
            if description.descriptor is copycat.slipnet["rightmost"]
        ),
    )
    monkeypatch.setattr(
        selected_codelet[0],
        "_get_modified_description",
        lambda modified_object, *_: next(
            description
            for description in modified_object.extrinsic_descriptions
            if description.description_type_related
            is copycat.slipnet["letter_category"]
            and description.relation is copycat.slipnet["successor"]
        ),
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 136
    assert any(
        isinstance(posted, RuleStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, RuleStrengthTester)
        and c.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 137
    assert any(
        isinstance(posted, RuleBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, RuleBuilder)
        and c.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 138
    assert copycat.workspace.rule.descriptor_1 is copycat.slipnet["rightmost"]
    assert (
        copycat.workspace.rule.replaced_description_type
        is copycat.slipnet["letter_category"]
    )
    assert copycat.workspace.rule.relation is copycat.slipnet["successor"]
    selected_codelet[0] = RuleTranslator(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 139
    assert (
        copycat.workspace.translated_rule.descriptor_1 is copycat.slipnet["rightmost"]
    )
    assert copycat.workspace.translated_rule.relation is copycat.slipnet["predecessor"]
    assert AnswerBuilder(copycat.slipnet, copycat.workspace).build() is None
    assert [
        letter.letter_category.name
        for letter in copycat.workspace.answer_string.letters
    ] == ["k", "j", "h"]
    assert copycat.coderack.number_of_codelets_run == 139
