"""
This test approximates the run of Copycat described on pages 123-138
of Mitchell 1993 'Analogy Making as Perception'
where Copycat responds to the problem
abc -> abd ==> xyz -> ?
with the answer
wyz
In this test, codelets are selected deterministically in order to
test interactions between codelets and workspace work correctly
The test was initially generated by Codex using GPT 5.6 with extra high reasoning
"""
from random import choice as random_choice
from random import choices as random_choices

from numpy.random import choice as numpy_random_choice
import pytest

from copycat import Copycat
from copycat.answer_builder import AnswerBuilder
from copycat.codelet_result import Finish, Fizzle, FizzleReason
from copycat.codelets import (
    BottomUpBondScout,
    BottomUpCorrespondenceScout,
    Breaker,
    ReplacementFinder,
    RuleScout,
    RuleTranslator,
    WholeStringGroupScout,
)
from copycat.codelets.builders import (
    BondBuilder,
    CorrespondenceBuilder,
    DescriptionBuilder,
    GroupBuilder,
    RuleBuilder,
)
from copycat.codelets.scouts.description_scouts import TopDownDescriptionScout
from copycat.codelets.strength_testers import (
    BondStrengthTester,
    CorrespondenceStrengthTester,
    DescriptionStrengthTester,
    GroupStrengthTester,
    RuleStrengthTester,
)
from copycat.snag_exception import SnagException


SLIPNET_JSON_FILE = "configs/slipnet.json"
CODERACK_JSON_FILE = "configs/coderack.json"
HYPERPARAMETERS_FILE = "configs/hyperparameters.json"


def test_single_run(monkeypatch):
    copycat = Copycat.from_json(
        SLIPNET_JSON_FILE, CODERACK_JSON_FILE, HYPERPARAMETERS_FILE
    )
    copycat._add_letters_to_workspace("abc -> abd ==> xyz -> ?")
    copycat._add_initial_descriptions_to_workspace()
    copycat._post_initial_codelets()

    selected_codelet = [None]
    chosen_items = []
    monkeypatch.setattr(
        "copycat.coderack.random.choice",
        lambda population: (
            selected_codelet[0]
            if selected_codelet[0] in population
            else next(item for item in chosen_items if item in population)
            if any(item in population for item in chosen_items)
            else random_choice(population)
        ),
    )
    monkeypatch.setattr(
        "copycat.coderack.random.choices",
        lambda population, weights=None, k=1: (
            [copycat.coderack.get_urgency_bin(selected_codelet[0].urgency_bin)]
            if population is copycat.coderack._urgency_bins
            else [next(item for item in chosen_items if item in population)]
            if any(item in population for item in chosen_items)
            else random_choices(population, weights=weights, k=k)
        ),
    )
    monkeypatch.setattr(
        "copycat.codelets.strength_testers.bond_strength_tester.random.random",
        lambda: 0.0,
    )
    monkeypatch.setattr(
        "copycat.codelets.scouts.description_scouts.top_down_description_scout.np.random.choice",
        lambda population, p=None: (
            next(item for item in chosen_items if item in population)
            if any(item in population for item in chosen_items)
            else numpy_random_choice(population, p=p)
        ),
    )

    a, b, c = copycat.workspace.initial_string.letters
    x, y, z = copycat.workspace.target_string.letters
    chosen_items[:] = [c]
    selected_codelet[0] = next(
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, ReplacementFinder)
    )
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 1
    assert c.replacement.target.letter_category is copycat.slipnet["d"]

    coderack_population = copycat.coderack.population
    for codelet_index in range(25):
        selected_codelet[0] = ReplacementFinder(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(
            FizzleReason.LETTER_ALREADY_HAS_REPLACEMENT
        )
        assert copycat.coderack.number_of_codelets_run == codelet_index + 2
        assert copycat.coderack.population == coderack_population
    chosen_items.clear()
    for codelet_index in range(25):
        selected_codelet[0] = WholeStringGroupScout(
            2, copycat.coderack, copycat.slipnet, copycat.workspace
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(FizzleReason.NO_BONDS)
        assert copycat.coderack.number_of_codelets_run == codelet_index + 27
        assert copycat.coderack.population == coderack_population
    for codelet_index in range(25):
        selected_codelet[0] = Breaker(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(FizzleReason.NO_STRUCTURES)
        assert copycat.coderack.number_of_codelets_run == codelet_index + 52
        assert copycat.coderack.population == coderack_population

    # Pages 124-126: Copycat first reaches the ordinary, same-direction
    # interpretation.  Both abc and xyz are right-going successor strings.
    for codelet_index, (source, target) in enumerate(((a, b), (b, c), (x, y), (y, z))):
        selected_codelet[0] = BottomUpBondScout(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        chosen_items[:] = [
            source,
            target,
            copycat.slipnet["letter_category"],
            True,
        ]
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 77 + codelet_index * 3
        assert (
            source.string.proposed_bonds[-1].bond_category
            is copycat.slipnet["successor"]
        )
        assert any(
            isinstance(posted, BondStrengthTester)
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, BondStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 78 + codelet_index * 3
        assert any(
            isinstance(posted, BondBuilder) for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, BondBuilder)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 79 + codelet_index * 3
        assert (
            source.string.bonds_by_role[source][target].bond_category
            is copycat.slipnet["successor"]
        )

    assert [
        bond.bond_category.name for bond in copycat.workspace.target_string.bonds
    ] == ["successor", "successor"]

    # Build the two first-view whole-string successor groups.
    for codelet_index, workspace_string in enumerate(
        (copycat.workspace.initial_string, copycat.workspace.target_string)
    ):
        chosen_items[:] = [workspace_string]
        selected_codelet[0] = WholeStringGroupScout(
            2, copycat.coderack, copycat.slipnet, copycat.workspace
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 89 + codelet_index * 3
        assert len(workspace_string.proposed_groups) == 1
        assert any(
            isinstance(posted, GroupStrengthTester)
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, GroupStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 90 + codelet_index * 3
        assert any(
            isinstance(posted, GroupBuilder) for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, GroupBuilder)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 91 + codelet_index * 3
        assert workspace_string.groups[-1].spans_whole_string()

    initial_group = copycat.workspace.initial_string.groups[-1]
    first_target_group = copycat.workspace.target_string.groups[-1]

    # Build the first whole-string group correspondence.
    chosen_items[:] = [initial_group, first_target_group]
    selected_codelet[0] = BottomUpCorrespondenceScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 95
    assert any(
        isinstance(posted, CorrespondenceStrengthTester)
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 96
    copycat.slipnet.update_activations()
    assert any(
        isinstance(posted, CorrespondenceBuilder)
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 97
    assert initial_group.correspondence is first_target_group.correspondence
    assert ("successor", "successor") in {
        (mapping.descriptor_1.name, mapping.descriptor_2.name)
        for mapping in initial_group.correspondence.accessory_concept_mappings
    }

    # Find the unchanged replacements before building the ordinary rule.
    for codelet_index, letter in enumerate((a, b)):
        chosen_items[:] = [letter]
        selected_codelet[0] = ReplacementFinder(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 98 + codelet_index
        assert letter.replacement.target.letter_category is letter.letter_category

    selected_codelet[0] = RuleScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    initial_description = next(
        description
        for description in selected_codelet[0]._get_initial_descriptions(c)
        if description.descriptor is copycat.slipnet["rightmost"]
    )
    modified_description = next(
        description
        for description in c.replacement.target.extrinsic_descriptions
        if description.description_type_related is copycat.slipnet["letter_category"]
        and description.relation is copycat.slipnet["successor"]
    )
    chosen_items[:] = [initial_description, modified_description]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 100
    assert any(
        isinstance(posted, RuleStrengthTester) for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, RuleStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 101
    assert any(isinstance(posted, RuleBuilder) for posted in copycat.coderack.codelets)
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, RuleBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 102
    assert copycat.workspace.rule.descriptor_1 is copycat.slipnet["rightmost"]
    assert copycat.workspace.rule.relation is copycat.slipnet["successor"]

    selected_codelet[0] = RuleTranslator(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 103
    assert (
        copycat.workspace.translated_rule.descriptor_1 is copycat.slipnet["rightmost"]
    )
    assert copycat.workspace.translated_rule.relation is copycat.slipnet["successor"]

    # Pages 126-129: successor(Z) does not exist.  The answer builder records z
    # as the snag object and raises; no answer letter is silently manufactured.
    with pytest.raises(SnagException):
        AnswerBuilder(copycat.slipnet, copycat.workspace).build()
    assert copycat.workspace.snag_objects == [z]
    assert copycat.workspace.answer_string.letters == []

    # Pages 130-136: the high-temperature breaker sequence removes the rule,
    # the no-slippage correspondence, and the target successor group.  Each
    # breaker is itself selected from the coderack and counted.
    for codelet_index, structure in enumerate(
        (
            copycat.workspace.rule,
            initial_group.correspondence,
            first_target_group,
        )
    ):
        chosen_items[:] = [structure]
        selected_codelet[0] = Breaker(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 104 + codelet_index

    assert copycat.workspace.rule is None
    assert initial_group.correspondence is None
    assert first_target_group not in copycat.workspace.target_string.groups
    assert x.group is None
    assert y.group is None
    assert z.group is None
    chosen_items.clear()

    # Pages 136-138: the target is rebuilt in the opposite direction.  Spatially
    # left-going predecessor bonds are proposed from y to x and from z to y.
    for codelet_index, (source, target) in enumerate(((y, x), (z, y))):
        selected_codelet[0] = BottomUpBondScout(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        chosen_items[:] = [
            source,
            target,
            copycat.slipnet["letter_category"],
            True,
        ]
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 107 + codelet_index * 3
        assert (
            source.string.proposed_bonds[-1].bond_category
            is copycat.slipnet["predecessor"]
        )
        assert any(
            isinstance(posted, BondStrengthTester)
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, BondStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 108 + codelet_index * 3
        assert any(
            isinstance(posted, BondBuilder) for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, BondBuilder)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 109 + codelet_index * 3
        assert (
            source.string.bonds_by_role[source][target].bond_category
            is copycat.slipnet["predecessor"]
        )

    assert [
        bond.bond_category.name for bond in copycat.workspace.target_string.bonds
    ] == ["predecessor", "predecessor"]

    # Rebuild xyz as the left-going predecessor group from the new bonds.
    chosen_items[:] = [copycat.workspace.target_string, x]
    selected_codelet[0] = WholeStringGroupScout(
        2, copycat.coderack, copycat.slipnet, copycat.workspace
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 113
    assert any(
        isinstance(posted, GroupStrengthTester) for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, GroupStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 114
    assert any(isinstance(posted, GroupBuilder) for posted in copycat.coderack.codelets)
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, GroupBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 115
    target_group = copycat.workspace.target_string.groups[-1]
    assert target_group.group_category is copycat.slipnet["predecessor_group"]
    assert target_group.direction_category is copycat.slipnet["left"]

    # Build the diagonal c-x correspondence that supplies the deep
    # rightmost -> leftmost mapping shown in frames 18-21.
    chosen_items[:] = [c, x]
    selected_codelet[0] = BottomUpCorrespondenceScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 116
    assert any(
        isinstance(posted, CorrespondenceStrengthTester)
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 117
    copycat.slipnet.update_activations()
    assert any(
        isinstance(posted, CorrespondenceBuilder)
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 118
    assert c.correspondence is x.correspondence
    assert ("rightmost", "leftmost") in {
        (mapping.descriptor_1.name, mapping.descriptor_2.name)
        for mapping in c.correspondence.concept_mappings
    }

    # Build the final whole-string group correspondence.
    chosen_items[:] = [initial_group, target_group]
    selected_codelet[0] = BottomUpCorrespondenceScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 119
    assert any(
        isinstance(posted, CorrespondenceStrengthTester)
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 120
    copycat.slipnet.update_activations()
    assert any(
        isinstance(posted, CorrespondenceBuilder)
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 121
    assert initial_group.correspondence is target_group.correspondence
    assert {
        (mapping.descriptor_1.name, mapping.descriptor_2.name)
        for mapping in initial_group.correspondence.concept_mappings
    }.issuperset(
        {
            ("successor_group", "predecessor_group"),
            ("right", "left"),
            ("successor", "predecessor"),
        }
    )

    selected_codelet[0] = RuleScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    initial_description = next(
        description
        for description in selected_codelet[0]._get_initial_descriptions(c)
        if description.descriptor is copycat.slipnet["rightmost"]
    )
    modified_description = next(
        description
        for description in c.replacement.target.extrinsic_descriptions
        if description.description_type_related is copycat.slipnet["letter_category"]
        and description.relation is copycat.slipnet["successor"]
    )
    chosen_items[:] = [initial_description, modified_description]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 176
    assert any(
        isinstance(posted, RuleStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, RuleStrengthTester)
        and c.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 177
    assert (
        selected_codelet[0].proposed_rule.descriptor_1 is copycat.slipnet["rightmost"]
    )
    assert selected_codelet[0].proposed_rule.relation is copycat.slipnet["successor"]
    assert any(
        isinstance(posted, RuleBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, RuleBuilder)
        and c.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 178
    selected_codelet[0] = RuleTranslator(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 179
    assert copycat.workspace.translated_rule.descriptor_1 is copycat.slipnet["leftmost"]
    assert copycat.workspace.translated_rule.relation is copycat.slipnet["predecessor"]
    assert AnswerBuilder(copycat.slipnet, copycat.workspace).build() is None
    assert [
        letter.letter_category.name
        for letter in copycat.workspace.answer_string.letters
    ] == ["w", "y", "z"]
    assert copycat.coderack.number_of_codelets_run == 179
