"""
This test approximates the run of Copycat described on pages 113-123
of Mitchell 1993 'Analogy Making as Perception'
where Copycat responds to the problem
abc -> abd ==> mrrjjj -> ?
with the answer
mrrjjjj
In this test, codelets are selected deterministically in order to
test interactions between codelets and workspace work correctly
The test was initially generated by Codex using GPT 5.6 with extra high reasoning
"""
from random import choice as random_choice
from random import choices as random_choices


from copycat import Copycat
from copycat.answer_builder import AnswerBuilder
from copycat.codelet_result import Finish, Fizzle, FizzleReason
from copycat.codelets import (
    BottomUpBondScout,
    BottomUpCorrespondenceScout,
    Breaker,
    ReplacementFinder,
    RuleScout,
    RuleTranslator,
    WholeStringGroupScout,
)
from copycat.codelets.builders import (
    BondBuilder,
    CorrespondenceBuilder,
    DescriptionBuilder,
    GroupBuilder,
    RuleBuilder,
)
from copycat.codelets.scouts.description_scouts import TopDownDescriptionScout
from copycat.codelets.scouts.group_scouts.top_down_category_group_scout import (
    TopDownCategoryGroupScout,
)
from copycat.codelets.strength_testers import (
    BondStrengthTester,
    CorrespondenceStrengthTester,
    DescriptionStrengthTester,
    GroupStrengthTester,
    RuleStrengthTester,
)


SLIPNET_JSON_FILE = "copycat/configs/slipnet.json"
CODERACK_JSON_FILE = "copycat/configs/coderack.json"
HYPERPARAMETERS_FILE = "copycat/configs/hyperparameters.json"


def test_single_run(monkeypatch):
    copycat = Copycat.from_json(
        SLIPNET_JSON_FILE, CODERACK_JSON_FILE, HYPERPARAMETERS_FILE
    )
    copycat._add_letters_to_workspace("abc -> abd ==> mrrjjj -> ?")
    copycat._add_initial_descriptions_to_workspace()
    copycat._post_initial_codelets()

    selected_codelet = [None]
    chosen_items = []
    monkeypatch.setattr(
        "copycat.coderack.random.choice",
        lambda population: (
            selected_codelet[0]
            if selected_codelet[0] in population
            else next(item for item in chosen_items if item in population)
            if any(item in population for item in chosen_items)
            else random_choice(population)
        ),
    )
    monkeypatch.setattr(
        "copycat.coderack.random.choices",
        lambda population, weights=None, k=1: (
            [copycat.coderack.get_urgency_bin(selected_codelet[0].urgency_bin)]
            if population is copycat.coderack._urgency_bins
            else [next(item for item in chosen_items if item in population)]
            if any(item in population for item in chosen_items)
            else random_choices(population, weights=weights, k=k)
        ),
    )
    monkeypatch.setattr(
        "copycat.codelets.strength_testers.bond_strength_tester.random.random",
        lambda: 0.0,
    )
    monkeypatch.setattr(
        "copycat.codelets.strength_testers.group_strength_tester.random.random",
        lambda: 0.0,
    )
    monkeypatch.setattr(
        "copycat.codelets.scouts.correspondence_scout.random.random",
        lambda: 0.0,
    )
    monkeypatch.setattr(
        "copycat.codelets.strength_testers.correspondence_strength_tester.random.random",
        lambda: 0.0,
    )
    monkeypatch.setattr(
        "copycat.codelets.scouts.description_scouts.top_down_description_scout.select_item_from_list",
        lambda population, weights: (
            next(item for item in chosen_items if item in population)
            if any(item in population for item in chosen_items)
            else random_choices(population, weights=weights, k=1)[0]
        ),
    )

    a, b, c = copycat.workspace.initial_string.letters
    m, r_1, r_2, j_1, j_2, j_3 = copycat.workspace.target_string.letters
    chosen_items[:] = [c]
    selected_codelet[0] = next(
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, ReplacementFinder)
    )
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 1
    assert c.replacement.target.letter_category is copycat.slipnet["d"]

    coderack_population = copycat.coderack.population
    for codelet_index in range(25):
        selected_codelet[0] = ReplacementFinder(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(
            FizzleReason.LETTER_ALREADY_HAS_REPLACEMENT
        )
        assert copycat.coderack.number_of_codelets_run == codelet_index + 2
        assert copycat.coderack.population == coderack_population
    chosen_items.clear()
    for codelet_index in range(25):
        selected_codelet[0] = WholeStringGroupScout(
            2, copycat.coderack, copycat.slipnet, copycat.workspace
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(FizzleReason.NO_BONDS)
        assert copycat.coderack.number_of_codelets_run == codelet_index + 27
        assert copycat.coderack.population == coderack_population
    for codelet_index in range(25):
        selected_codelet[0] = Breaker(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(FizzleReason.NO_STRUCTURES)
        assert copycat.coderack.number_of_codelets_run == codelet_index + 52
        assert copycat.coderack.population == coderack_population

    # Pages 113-123: build the rr and jjj sameness fabrics whose lengths
    # become the relevant relation, alongside the initial successor fabric.
    for codelet_index, (source, target, category) in enumerate(
        (
            (a, b, "successor"),
            (b, c, "successor"),
            (r_1, r_2, "sameness"),
            (j_1, j_2, "sameness"),
            (j_2, j_3, "sameness"),
        )
    ):
        selected_codelet[0] = BottomUpBondScout(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        chosen_items[:] = [source, target, copycat.slipnet["letter_category"]]
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 77 + codelet_index * 3
        assert (
            source.string.proposed_bonds[-1].bond_category is copycat.slipnet[category]
        )
        assert any(
            isinstance(posted, BondStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, BondStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 78 + codelet_index * 3
        assert any(
            isinstance(posted, BondBuilder) for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, BondBuilder)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 79 + codelet_index * 3
        assert (
            source.string.bonds_by_role[source][target].bond_category
            is copycat.slipnet[category]
        )

    assert [
        bond.bond_category.name for bond in copycat.workspace.target_string.bonds
    ] == ["sameness", "sameness", "sameness"]

    # Pages 115-117: first build the R and J sameness groups.  Each scout
    # posts the strength tester selected next, and each tester posts the
    # builder selected after it.
    for codelet_index, (first_letter, number_of_bonds) in enumerate(
        ((r_1, 1), (j_1, 2))
    ):
        selected_codelet[0] = TopDownCategoryGroupScout(
            2,
            copycat.coderack,
            copycat.slipnet,
            copycat.workspace,
            copycat.slipnet["sameness_group"],
        )
        chosen_items[:] = [
            copycat.workspace.target_string,
            first_letter,
            number_of_bonds,
            copycat.slipnet["right"],
        ]
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 92 + codelet_index * 3
        assert any(
            isinstance(posted, GroupStrengthTester)
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, GroupStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 93 + codelet_index * 3
        assert any(
            isinstance(posted, GroupBuilder) for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, GroupBuilder)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 94 + codelet_index * 3

    r_group = next(
        group
        for group in copycat.workspace.target_string.groups
        if (group.left_position, group.right_position) == (1, 2)
    )
    j_group = next(
        group
        for group in copycat.workspace.target_string.groups
        if (group.left_position, group.right_position) == (3, 5)
    )
    assert r_group.group_category is copycat.slipnet["sameness_group"]
    assert j_group.group_category is copycat.slipnet["sameness_group"]

    # Pages 117-119: pressure from the two sameness groups must overcome the
    # usual resistance to a one-letter sameness group around m.  This is kept
    # as a real scout assertion: if singleton groups are not implemented, the
    # test must fail here rather than manufacturing the group in the test.
    selected_codelet[0] = TopDownCategoryGroupScout(
        2,
        copycat.coderack,
        copycat.slipnet,
        copycat.workspace,
        copycat.slipnet["sameness_group"],
    )
    chosen_items[:] = [copycat.workspace.target_string, m]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 98
    assert any(
        isinstance(posted, GroupStrengthTester) for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, GroupStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 99
    assert any(isinstance(posted, GroupBuilder) for posted in copycat.coderack.codelets)
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, GroupBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 100

    m_group = next(
        group
        for group in copycat.workspace.target_string.groups
        if (group.left_position, group.right_position) == (0, 0)
    )
    assert m_group.group_category is copycat.slipnet["sameness_group"]

    # Pages 118-120: length becomes active and descriptions 1, 2, and 3 are
    # attached to M, R, and J by description scouts, testers, and builders.
    for codelet_index, (group, descriptor) in enumerate(
        (
            (m_group, copycat.slipnet["one"]),
            (r_group, copycat.slipnet["two"]),
            (j_group, copycat.slipnet["three"]),
        )
    ):
        chosen_items[:] = [group, descriptor]
        selected_codelet[0] = TopDownDescriptionScout(
            2,
            copycat.coderack,
            copycat.slipnet,
            copycat.workspace,
            copycat.slipnet["length"],
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 101 + codelet_index * 3
        assert any(
            isinstance(posted, DescriptionStrengthTester)
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, DescriptionStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 102 + codelet_index * 3
        assert any(
            isinstance(posted, DescriptionBuilder)
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, DescriptionBuilder)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 103 + codelet_index * 3
        assert group.get_descriptor(copycat.slipnet["length"]) is descriptor

    # Pages 118-119: the a-M correspondence turns the initial letter into a
    # target singleton group.  Its letter-to-group slippage is needed when the
    # rule is translated from the initial string to the target string.
    chosen_items[:] = [a, m_group]
    for description in a.descriptions + m_group.descriptions:
        description.descriptor.activation = 1.0
    selected_codelet[0] = BottomUpCorrespondenceScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 110
    proposed_correspondence = copycat.workspace.proposed_correspondences[-1]
    assert proposed_correspondence.source is a
    assert proposed_correspondence.target is m_group
    assert any(
        isinstance(posted, CorrespondenceStrengthTester)
        and posted.proposed_correspondence is proposed_correspondence
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = next(
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceStrengthTester)
        and posted.proposed_correspondence is proposed_correspondence
    )
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 111
    copycat.slipnet.update_activations()
    assert any(
        isinstance(posted, CorrespondenceBuilder)
        and posted.proposed_correspondence is proposed_correspondence
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = next(
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceBuilder)
        and posted.proposed_correspondence is proposed_correspondence
    )
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 112
    assert a.correspondence is m_group.correspondence
    assert ("letter", "group") in {
        (mapping.descriptor_1.name, mapping.descriptor_2.name)
        for mapping in a.correspondence.concept_mappings
    }

    # Pages 120-122: the group lengths themselves form a successor sequence,
    # first 1-2 and then 2-3.
    for codelet_index, (source_group, target_group) in enumerate(
        ((m_group, r_group), (r_group, j_group))
    ):
        selected_codelet[0] = BottomUpBondScout(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        chosen_items[:] = [source_group, target_group, copycat.slipnet["length"]]
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 113 + codelet_index * 3
        assert (
            source_group.string.proposed_bonds[-1].bond_facet
            is copycat.slipnet["length"]
        )
        assert any(
            isinstance(posted, BondStrengthTester)
            for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, BondStrengthTester)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 114 + codelet_index * 3
        assert any(
            isinstance(posted, BondBuilder) for posted in copycat.coderack.codelets
        )
        selected_codelet[0] = [
            posted
            for posted in copycat.coderack.codelets
            if isinstance(posted, BondBuilder)
            and posted.birth_time == copycat.coderack.number_of_codelets_run
        ][-1]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 115 + codelet_index * 3
        assert (
            source_group.string.bonds_by_role[source_group][target_group].bond_category
            is copycat.slipnet["successor"]
        )

    # Build the initial whole-string group from letter-category bonds.
    chosen_items[:] = [copycat.workspace.initial_string, a]
    selected_codelet[0] = WholeStringGroupScout(
        2, copycat.coderack, copycat.slipnet, copycat.workspace
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 119
    assert any(
        isinstance(posted, GroupStrengthTester) for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, GroupStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 120
    assert any(
        isinstance(posted, GroupBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, GroupBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 121
    initial_group = copycat.workspace.initial_string.groups[-1]
    assert initial_group.spans_whole_string()

    # Build the target whole-string group from the two length bonds.  This
    # assertion deliberately exercises nested groups; a letter-count-only
    # whole-string scout is an implementation defect and must fail the test.
    chosen_items[:] = [copycat.workspace.target_string, m_group]
    selected_codelet[0] = WholeStringGroupScout(
        2, copycat.coderack, copycat.slipnet, copycat.workspace
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 122
    assert any(
        isinstance(posted, GroupStrengthTester) for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, GroupStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 123
    assert any(
        isinstance(posted, GroupBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, GroupBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 124
    target_group = next(
        group
        for group in copycat.workspace.target_string.groups
        if group.spans_whole_string()
    )

    chosen_items[:] = [initial_group, target_group]
    selected_codelet[0] = BottomUpCorrespondenceScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 125
    assert any(
        isinstance(posted, CorrespondenceStrengthTester)
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 126
    copycat.slipnet.update_activations()
    assert any(
        isinstance(posted, CorrespondenceBuilder)
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        posted
        for posted in copycat.coderack.codelets
        if isinstance(posted, CorrespondenceBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 127
    assert initial_group.correspondence is target_group.correspondence
    assert ("letter_category", "length") in {
        (slippage.descriptor_1.name, slippage.descriptor_2.name)
        for slippage in copycat.workspace.slippages
    }
    assert {
        (mapping.descriptor_1.name, mapping.descriptor_2.name)
        for mapping in initial_group.correspondence.concept_mappings
    }.issuperset({("three", "three")})
    assert ("successor", "successor") in {
        (mapping.descriptor_1.name, mapping.descriptor_2.name)
        for mapping in initial_group.correspondence.accessory_concept_mappings
    }

    # Find the two unchanged replacements before proposing the rule.
    for codelet_index, letter in enumerate((a, b)):
        chosen_items[:] = [letter]
        selected_codelet[0] = ReplacementFinder(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 128 + codelet_index
        assert letter.replacement.target.letter_category is letter.letter_category

    selected_codelet[0] = RuleScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    initial_description = next(
        description
        for description in c.rule_initial_string_descriptions
        if description.descriptor is copycat.slipnet["rightmost"]
    )
    modified_description = next(
        description
        for description in c.replacement.target.extrinsic_descriptions
        if description.description_type_related is copycat.slipnet["letter_category"]
        and description.relation is copycat.slipnet["successor"]
    )
    chosen_items[:] = [initial_description, modified_description]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 130
    assert any(
        isinstance(posted, RuleStrengthTester)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, RuleStrengthTester)
        and c.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 131
    assert (
        selected_codelet[0].proposed_rule.descriptor_1 is copycat.slipnet["rightmost"]
    )
    assert (
        selected_codelet[0].proposed_rule.replaced_description_type
        is copycat.slipnet["letter_category"]
    )
    assert selected_codelet[0].proposed_rule.relation is copycat.slipnet["successor"]
    assert any(
        isinstance(posted, RuleBuilder)
        and posted.birth_time == copycat.coderack.number_of_codelets_run
        for posted in copycat.coderack.codelets
    )
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, RuleBuilder)
        and c.birth_time == copycat.coderack.number_of_codelets_run
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 132
    selected_codelet[0] = RuleTranslator(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 133
    assert (
        copycat.workspace.translated_rule.object_category_1 is copycat.slipnet["group"]
    )
    assert (
        copycat.workspace.translated_rule.descriptor_1 is copycat.slipnet["rightmost"]
    )
    assert (
        copycat.workspace.translated_rule.replaced_description_type
        is copycat.slipnet["length"]
    )
    assert copycat.workspace.translated_rule.relation is copycat.slipnet["successor"]
    assert AnswerBuilder(copycat.slipnet, copycat.workspace).build() is None
    assert [
        letter.letter_category.name
        for letter in copycat.workspace.answer_string.letters
    ] == ["m", "r", "r", "j", "j", "j", "j"]
