"""
This test approximates the run of Copycat described on pages 96-105
of Mitchell 1993 'Analogy Making as Perception'
where Copycat responds to the problem
abc -> abd ==> iijjkk -> ?
with the answer
iijjll
In this test, codelets are selected deterministically in order to
test interactions between codelets and workspace work correctly
The test was initially generated by Codex using GPT 5.6 with extra high reasoning
"""
from random import choice as random_choice
from random import choices as random_choices

from copycat import Copycat
from copycat.answer_builder import AnswerBuilder
from copycat.codelet_result import Finish, Fizzle, FizzleReason
from copycat.codelets import (
    BottomUpBondScout,
    BottomUpCorrespondenceScout,
    Breaker,
    ReplacementFinder,
    RuleScout,
    RuleTranslator,
    WholeStringGroupScout,
)
from copycat.codelets.builders import (
    BondBuilder,
    CorrespondenceBuilder,
    GroupBuilder,
    RuleBuilder,
)
from copycat.codelets.scouts.group_scouts.top_down_category_group_scout import (
    TopDownCategoryGroupScout,
)
from copycat.codelets.strength_testers import (
    BondStrengthTester,
    CorrespondenceStrengthTester,
    GroupStrengthTester,
    RuleStrengthTester,
)


SLIPNET_JSON_FILE = "configs/slipnet.json"
CODERACK_JSON_FILE = "configs/coderack.json"
HYPERPARAMETERS_FILE = "configs/hyperparameters.json"


def test_single_run(monkeypatch):
    copycat = Copycat.from_json(
        SLIPNET_JSON_FILE, CODERACK_JSON_FILE, HYPERPARAMETERS_FILE
    )
    copycat._add_letters_to_workspace("abc -> abd ==> iijjkk -> ?")
    copycat._add_initial_descriptions_to_workspace()
    copycat._post_initial_codelets()
    copycat.slipnet.update_activations()

    selected_codelet = [None]
    chosen_items = []
    monkeypatch.setattr(
        "copycat.coderack.random.choice",
        lambda population: (
            selected_codelet[0]
            if selected_codelet[0] in population
            else next(item for item in chosen_items if item in population)
            if any(item in population for item in chosen_items)
            else random_choice(population)
        ),
    )
    monkeypatch.setattr(
        "copycat.coderack.random.choices",
        lambda population, weights=None, k=1: (
            [copycat.coderack.get_urgency_bin(selected_codelet[0].urgency_bin)]
            if population is copycat.coderack._urgency_bins
            else [next(item for item in chosen_items if item in population)]
            if any(item in population for item in chosen_items)
            else random_choices(population, weights=weights, k=k)
        ),
    )
    monkeypatch.setattr(
        "copycat.codelets.strength_testers.bond_strength_tester.random.random",
        lambda: 0.0,
    )
    monkeypatch.setattr(
        "copycat.codelets.strength_testers.correspondence_strength_tester.random.random",
        lambda: 0.0,
    )

    # The changed rightmost letter supplies the successor relation in abc -> abd.
    a, b, c = copycat.workspace.initial_string.letters
    chosen_items[:] = [c]
    selected_codelet[0] = next(
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, ReplacementFinder)
    )
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 1
    assert c.replacement.target.letter_category is copycat.slipnet["d"]

    # As in the book's representative run, these exploratory codelets occur
    # before the first durable structures are built.
    coderack_population = copycat.coderack.population
    chosen_items[:] = [c]
    for codelet_index in range(25):
        selected_codelet[0] = ReplacementFinder(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(
            FizzleReason.LETTER_ALREADY_HAS_REPLACEMENT
        )
        assert copycat.coderack.number_of_codelets_run == codelet_index + 2
        assert copycat.coderack.population == coderack_population

    chosen_items.clear()
    for codelet_index in range(25):
        selected_codelet[0] = WholeStringGroupScout(
            2, copycat.coderack, copycat.slipnet, copycat.workspace
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(FizzleReason.NO_BONDS)
        assert copycat.coderack.number_of_codelets_run == codelet_index + 27
        assert copycat.coderack.population == coderack_population

    for codelet_index in range(25):
        selected_codelet[0] = Breaker(
            2, copycat.coderack, copycat.workspace, copycat.slipnet
        )
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Fizzle(FizzleReason.NO_STRUCTURES)
        assert copycat.coderack.number_of_codelets_run == codelet_index + 52
        assert copycat.coderack.population == coderack_population

    # a-b successor bond: scout, strength tester, builder.
    selected_codelet[0] = BottomUpBondScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    chosen_items[:] = [a, b, copycat.slipnet["letter_category"]]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 77
    selected_codelet[0] = next(
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, BondStrengthTester)
    )
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 78
    selected_codelet[0] = next(
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, BondBuilder)
    )
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 79
    assert a.right_bond is b.left_bond
    assert a.right_bond.bond_category is copycat.slipnet["successor"]

    # b-c successor bond: scout, strength tester, builder.
    selected_codelet[0] = BottomUpBondScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    chosen_items[:] = [b, c, copycat.slipnet["letter_category"]]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 80
    selected_codelet[0] = [
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, BondStrengthTester)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 81
    selected_codelet[0] = [
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, BondBuilder)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 82
    assert b.right_bond is c.left_bond

    # i-i sameness bond: scout, strength tester, builder.
    i_1, i_2, j_1, j_2, k_1, k_2 = copycat.workspace.target_string.letters
    selected_codelet[0] = BottomUpBondScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    chosen_items[:] = [i_1, i_2, copycat.slipnet["letter_category"]]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 83
    selected_codelet[0] = [
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, BondStrengthTester)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 84
    selected_codelet[0] = [
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, BondBuilder)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 85
    assert i_1.right_bond is i_2.left_bond
    assert i_1.right_bond.bond_category is copycat.slipnet["sameness"]

    # j-j sameness bond: scout, strength tester, builder.
    selected_codelet[0] = BottomUpBondScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    chosen_items[:] = [j_1, j_2, copycat.slipnet["letter_category"]]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 86
    selected_codelet[0] = [
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, BondStrengthTester)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 87
    selected_codelet[0] = [
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, BondBuilder)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 88
    assert j_1.right_bond is j_2.left_bond
    assert j_1.right_bond.bond_category is copycat.slipnet["sameness"]

    # k-k sameness bond: scout, strength tester, builder.
    selected_codelet[0] = BottomUpBondScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    chosen_items[:] = [k_1, k_2, copycat.slipnet["letter_category"]]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 89
    selected_codelet[0] = [
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, BondStrengthTester)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 90
    selected_codelet[0] = [
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, BondBuilder)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 91
    assert k_1.right_bond is k_2.left_bond
    assert k_1.right_bond.bond_category is copycat.slipnet["sameness"]

    # The next book structure is the directionless i-i sameness group.  This
    # codelet is expected to propose it directly from the selected i-i bond.
    selected_codelet[0] = TopDownCategoryGroupScout(
        2,
        copycat.coderack,
        copycat.slipnet,
        copycat.workspace,
        copycat.slipnet["sameness_group"],
    )
    chosen_items[:] = [copycat.workspace.target_string, i_1, 1]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 92

    # Build the three sameness groups, I, J, and K, from their selected bonds.
    for codelet_index, letter in enumerate((i_1, j_1, k_1)):
        selected_codelet[0] = TopDownCategoryGroupScout(
            2,
            copycat.coderack,
            copycat.slipnet,
            copycat.workspace,
            copycat.slipnet["sameness_group"],
        )
        chosen_items[:] = [
            copycat.workspace.target_string,
            letter,
            copycat.slipnet["right"],
            1,
        ]
        copycat.coderack.post(selected_codelet[0], temperature=0.0)
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 93 + codelet_index * 3
        proposed_group = copycat.workspace.target_string.proposed_groups[-1]
        selected_codelet[0] = [
            codelet
            for codelet in copycat.coderack.codelets
            if isinstance(codelet, GroupStrengthTester)
            and codelet.proposed_group is proposed_group
        ][0]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 94 + codelet_index * 3
        selected_codelet[0] = [
            codelet
            for codelet in copycat.coderack.codelets
            if isinstance(codelet, GroupBuilder)
            and codelet.proposed_group is proposed_group
        ][0]
        codelet = copycat.coderack.choose(temperature=0.0)
        assert codelet is selected_codelet[0]
        assert codelet.run(temperature=0.0) == Finish()
        assert copycat.coderack.number_of_codelets_run == 95 + codelet_index * 3

    i_group, j_group, k_group = copycat.workspace.target_string.groups
    assert [group.group_category for group in (i_group, j_group, k_group)] == [
        copycat.slipnet["sameness_group"],
        copycat.slipnet["sameness_group"],
        copycat.slipnet["sameness_group"],
    ]

    # I-J successor bond: scout, strength tester, builder.
    selected_codelet[0] = BottomUpBondScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    chosen_items[:] = [i_group, j_group, copycat.slipnet["letter_category"]]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 102
    selected_codelet[0] = [
        c for c in copycat.coderack.codelets if isinstance(c, BondStrengthTester)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 103
    selected_codelet[0] = [
        c for c in copycat.coderack.codelets if isinstance(c, BondBuilder)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 104

    # J-K successor bond: scout, strength tester, builder.
    selected_codelet[0] = BottomUpBondScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    chosen_items[:] = [j_group, k_group, copycat.slipnet["letter_category"]]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 105
    selected_codelet[0] = [
        c for c in copycat.coderack.codelets if isinstance(c, BondStrengthTester)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 106
    selected_codelet[0] = [
        c for c in copycat.coderack.codelets if isinstance(c, BondBuilder)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 107

    # The c-K correspondence supplies the letter-to-group slippage used to
    # translate the rule from the rightmost letter to the rightmost group.
    chosen_items[:] = [c, k_group]
    for description in c.descriptions + k_group.descriptions:
        description.descriptor.activation = 1.0
    selected_codelet[0] = BottomUpCorrespondenceScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 108
    proposed_correspondence = copycat.workspace.proposed_correspondences[-1]
    selected_codelet[0] = [
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, CorrespondenceStrengthTester)
        and codelet.proposed_correspondence is proposed_correspondence
    ][0]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 109
    copycat.slipnet.update_activations()
    selected_codelet[0] = [
        codelet
        for codelet in copycat.coderack.codelets
        if isinstance(codelet, CorrespondenceBuilder)
        and codelet.proposed_correspondence is proposed_correspondence
    ][0]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 110
    assert c.correspondence is k_group.correspondence

    # Whole target-string successor group: scout, strength tester, builder.
    chosen_items[:] = [copycat.workspace.target_string, i_group]
    selected_codelet[0] = WholeStringGroupScout(
        2, copycat.coderack, copycat.slipnet, copycat.workspace
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 111
    proposed_target_group = copycat.workspace.target_string.proposed_groups[-1]
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, GroupStrengthTester)
        and c.proposed_group is proposed_target_group
    ][0]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 112
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, GroupBuilder) and c.proposed_group is proposed_target_group
    ][0]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 113
    target_group = copycat.workspace.target_string.groups[-1]
    assert target_group.spans_whole_string()

    # Whole initial-string successor group: scout, strength tester, builder.
    chosen_items[:] = [copycat.workspace.initial_string, a]
    selected_codelet[0] = WholeStringGroupScout(
        2, copycat.coderack, copycat.slipnet, copycat.workspace
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 114
    proposed_initial_group = copycat.workspace.initial_string.proposed_groups[-1]
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, GroupStrengthTester)
        and c.proposed_group is proposed_initial_group
    ][0]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 115
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, GroupBuilder) and c.proposed_group is proposed_initial_group
    ][0]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 116
    initial_group = copycat.workspace.initial_string.groups[-1]

    # Continued consideration of c-K keeps rightmost active while the
    # whole-string correspondence is tested and built.
    chosen_items[:] = [c, k_group]
    for description in c.descriptions + k_group.descriptions:
        description.descriptor.activation = 1.0
    selected_codelet[0] = BottomUpCorrespondenceScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 117

    # Whole-string correspondence: scout, strength tester, builder.
    chosen_items[:] = [initial_group, target_group]
    for description in initial_group.descriptions + target_group.descriptions:
        description.descriptor.activation = 1.0
    selected_codelet[0] = BottomUpCorrespondenceScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 118
    proposed_whole_correspondence = copycat.workspace.proposed_correspondences[-1]
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, CorrespondenceStrengthTester)
        and c.proposed_correspondence is proposed_whole_correspondence
    ][0]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 119
    copycat.slipnet.update_activations()
    selected_codelet[0] = [
        c
        for c in copycat.coderack.codelets
        if isinstance(c, CorrespondenceBuilder)
        and c.proposed_correspondence is proposed_whole_correspondence
    ][0]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 120

    # Find the unchanged replacements, induce the rule, translate it, and build the answer.
    chosen_items[:] = [a]
    selected_codelet[0] = ReplacementFinder(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 121
    chosen_items[:] = [b]
    selected_codelet[0] = ReplacementFinder(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 122
    selected_codelet[0] = RuleScout(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    initial_description = next(
        description
        for description in c.rule_initial_string_descriptions
        if description.descriptor is copycat.slipnet["rightmost"]
    )
    modified_description = next(
        description
        for description in c.replacement.target.extrinsic_descriptions
        if description.description_type_related is copycat.slipnet["letter_category"]
        and description.relation is copycat.slipnet["successor"]
    )
    chosen_items[:] = [initial_description, modified_description]
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 123
    selected_codelet[0] = [
        c for c in copycat.coderack.codelets if isinstance(c, RuleStrengthTester)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 124
    selected_codelet[0] = [
        c for c in copycat.coderack.codelets if isinstance(c, RuleBuilder)
    ][-1]
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 125
    selected_codelet[0] = RuleTranslator(
        2, copycat.coderack, copycat.workspace, copycat.slipnet
    )
    copycat.coderack.post(selected_codelet[0], temperature=0.0)
    codelet = copycat.coderack.choose(temperature=0.0)
    assert codelet is selected_codelet[0]
    assert codelet.run(temperature=0.0) == Finish()
    assert copycat.coderack.number_of_codelets_run == 126
    assert AnswerBuilder(copycat.slipnet, copycat.workspace).build() is None
    assert [
        letter.letter_category.name
        for letter in copycat.workspace.answer_string.letters
    ] == ["i", "i", "j", "j", "l", "l"]
